version: '3.1'

services:
  app:
    image: 'springboot-postgresql'
    build: ./
    container_name: customer-app
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
  postgres-db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=testNew